<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.pay4j</groupId>
        <artifactId>pay4j-modules</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>pay4j-demo</artifactId>

    <description>
        demo模块
    </description>

    <dependencies>

        <!-- 通用工具-->
        <dependency>
            <groupId>com.pay4j</groupId>
            <artifactId>pay4j-common-core</artifactId>
        </dependency>

        <!-- api模块 -->
        <dependency>
            <groupId>com.pay4j</groupId>
            <artifactId>pay4j-api</artifactId>
        </dependency>

        <!-- 接口模块 -->
        <dependency>
            <groupId>com.pay4j</groupId>
            <artifactId>pay4j-common-doc</artifactId>
        </dependency>

        <!-- 短信模块 -->
        <dependency>
            <groupId>com.pay4j</groupId>
            <artifactId>pay4j-common-sms</artifactId>
        </dependency>

        <!-- 邮件服务 -->
        <dependency>
            <groupId>com.pay4j</groupId>
            <artifactId>pay4j-common-mail</artifactId>
        </dependency>

        <!-- 缓存服务 -->
        <dependency>
            <groupId>com.pay4j</groupId>
            <artifactId>pay4j-common-redis</artifactId>
        </dependency>

        <!-- 数据库服务 -->
        <dependency>
            <groupId>com.pay4j</groupId>
            <artifactId>pay4j-common-mybatis</artifactId>
        </dependency>

        <!-- 日志记录 -->
        <dependency>
            <groupId>com.pay4j</groupId>
            <artifactId>pay4j-common-log</artifactId>
        </dependency>

        <!-- excel -->
        <dependency>
            <groupId>com.pay4j</groupId>
            <artifactId>pay4j-common-excel</artifactId>
        </dependency>

        <!-- 安全模块 -->
        <dependency>
            <groupId>com.pay4j</groupId>
            <artifactId>pay4j-common-security</artifactId>
        </dependency>

        <!-- web服务 -->
        <dependency>
            <groupId>com.pay4j</groupId>
            <artifactId>pay4j-common-web</artifactId>
        </dependency>

        <!-- 翻译模块 -->
        <dependency>
            <groupId>com.pay4j</groupId>
            <artifactId>pay4j-common-translation</artifactId>
        </dependency>

        <!-- 脱敏模块 -->
        <dependency>
            <groupId>com.pay4j</groupId>
            <artifactId>pay4j-common-sensitive</artifactId>
        </dependency>

        <!-- 数据库加解密模块 -->
        <dependency>
            <groupId>com.pay4j</groupId>
            <artifactId>pay4j-common-encrypt</artifactId>
        </dependency>

        <!-- ES搜索引擎服务 -->
        <dependency>
            <groupId>com.pay4j</groupId>
            <artifactId>pay4j-common-elasticsearch</artifactId>
        </dependency>

        <!-- 消息推送模块 -->
        <dependency>
            <groupId>com.pay4j</groupId>
            <artifactId>pay4j-common-push</artifactId>
        </dependency>

        <!-- mqtt模块 -->
        <dependency>
            <groupId>com.pay4j</groupId>
            <artifactId>pay4j-common-mqtt</artifactId>
        </dependency>

        <!-- mcp模块 -->
        <dependency>
            <groupId>com.pay4j</groupId>
            <artifactId>pay4j-common-mcp</artifactId>
        </dependency>

    </dependencies>

</project>
